### ISSUE TITLE
Debug help needed

### ISSUE THREAD

**Issue by RishuK** [marcushellberg/java-ai-playground#11]
Seeing this message on the browser when I try to set this up locally: 
Could you please help? 

Expecting to the see the GridColumns..

![Screenshot 2024-06-08 at 11 47 48 PM](https://github.com/marcushellberg/java-ai-playground/assets/8846064/3ed25763-180f-40ff-9eff-f3e5fc1296fe)

No routes found
You can bootstrap a basic frontend by using one of these commands:

    gradle hillaInitApp

    mvn hilla:init-app
    
Learn more at https://hilla.dev/docs.

**Comment by marcushellberg** [comment]
Which branch are you using? How are you starting the application?
