### ISSUE TITLE
Spring AI is not keeping conversation

### ISSUE THREAD

**Issue by ygoron360** [marcushellberg/java-ai-playground#5]
For me LangChain4j version works but Sping AI is not keeping conversation. 

<img width="2483" alt="image" src="https://github.com/marcushellberg/java-ai-playground/assets/155498144/b57b32e8-f8bc-4b4b-bb02-dc4c3f2cdc5e">

<img width="2470" alt="image" src="https://github.com/marcushellberg/java-ai-playground/assets/155498144/8d42bab2-54dd-43c9-a8ce-2526ec196e29">

**Comment by marcushellberg** [comment]
Thanks for reporting. Let me look into it

**Comment by marcushellberg** [comment]
Should be fixed now, hopefully.

**Comment by ygoron360** [comment]
> Should be fixed now, hopefully.

Works great - thanks! Great example BTW

**Comment by marcushellberg** [comment]
Glad it worked. Thanks for reporting!

**Comment by ygoron360** [comment]
> Glad it worked. Thanks for reporting!

I still think that history is a bit funky for spring. I’ve tried to change to spring-ai-openai to spring-ai-ollama and history stop working. Did not have time to investigate myself yet. Clearly langchain4j has much better support for history.

**Comment by marcushellberg** [comment]
Spring AI doesn't have any built-in support for history yet. The one in the project is contributed by one of the Spring AI team members, and I did a few changes to it, so it may be the reason
